import type { DashboardData, CountryData, CountrySummary } from "@/app/lib/types";

// Import the generated JSON — resolved at build time
// This file is generated by scripts/fetch-data.ts
let _data: DashboardData | null = null;

function loadData(): DashboardData {
  if (_data) return _data;
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    _data = require("@/generated/corruption-data.json") as DashboardData;
    return _data;
  } catch {
    console.warn("corruption-data.json not found — returning empty data");
    return { countries: [], totalCases: 0, generatedAt: "" };
  }
}

/** Full dashboard data */
export function getDashboardData(): DashboardData {
  return loadData();
}

/** Summary for map rendering (lightweight) */
export function getCountrySummaries(): CountrySummary[] {
  return loadData().countries.map(({ slug, name, isoA2, caseCount }) => ({
    slug,
    name,
    isoA2,
    caseCount,
  }));
}

/** Full country data by slug */
export function getCountryBySlug(slug: string): CountryData | undefined {
  return loadData().countries.find((c) => c.slug === slug);
}

/** All slugs for generateStaticParams */
export function getAllSlugs(): string[] {
  return loadData().countries.map((c) => c.slug);
}

/** Max case count across all countries (for color scale domain) */
export function getMaxCaseCount(): number {
  const data = loadData();
  if (data.countries.length === 0) return 1;
  return Math.max(...data.countries.map((c) => c.caseCount));
}
